### ISSUE TITLE
DartError: Bad state: Could not find a emscripten module named dicom_ffi

### ISSUE THREAD

**Issue by feliwir** [vm75/native.dart#7]
Hey, i did compile my source with `emcmake` to JS + WASM files. When loading the file i get the following error:
```
DartError: Bad state: Could not find a emscripten module named dicom_ffi
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 288:3  throw_
packages/wasm_ffi/src/ffi/modules/emscripten_module.dart 71:7                _getModuleFunction
packages/wasm_ffi/src/ffi/modules/emscripten_module.dart 80:28               <fn>
```

Those are my WASM files:
[dicom_ffi.zip](https://github.com/user-attachments/files/17071352/dicom_ffi.zip)

Do i need any special flags when compiling with Emscripten? Could you maybe add a description how you've compiled the WASM inside the example? Thanks

**Comment by vm75** [comment]
Hi @feliwir , thanks for reporting this. I will look into it

**Comment by vm75** [comment]
Can you share a minimal project?

**Comment by vm75** [comment]
@feliwir , 
It is important to pass the -s MODULARIZE=1 directive to emcc and also give the module a name using -s EXPORT_NAME=dicom_ffi
