### ISSUE TITLE
[Feature request] Add support for `DynamicLibrary.process()`

### ISSUE THREAD

**Issue by CaptainDario** [vm75/native.dart#9]
Basically, what the title says, on native platforms we can use `DynamicLibrary.process()` which should be accessible in this package for native platforms.

**Comment by CaptainDario** [comment]
My current workaround looks like this (it should be easy to add something similar to this package)

**ffi_lib_stub.dart**
```dart
export 'ffi_lib_native.dart' if (dart.library.js_interop) 'ffi_lib_wasm.dart';
```

**ffi_lib_native.dart**
``` dart
import 'dart:io';
import 'dart:async';

import 'dart:ffi' as native_ffi;
import 'package:wasm_ffi/ffi_bridge.dart';
import 'package:wasm_ffi/ffi_wrapper.dart';



Future<DynamicLibrary> loadMecabDartLib () async {

  if(Platform.isAndroid){
    return (await FfiWrapper.load("lib")).library;
  }
  else if(Platform.isWindows) {
    return (await FfiWrapper.load("lib")).library;
  }
  else {
    return  native_ffi.DynamicLibrary.process() as DynamicLibrary;
  }
}
```

**ffi_lib_wasm.dart**
``` dart
import 'dart:async';

import 'package:wasm_ffi/ffi.dart';
import 'package:wasm_ffi/ffi_wrapper.dart';



Future<DynamicLibrary> loadMecabDartLib () async {

  return (await FfiWrapper.load("")).library;
  
}
```

Thank you for your efforts!

**Comment by vm75** [comment]
@CaptainDario 
i have tried something here. now FfiWrapper.load can be given overrides for some platforms. if you override with empty string for iOS and Android, it should resort to loading statically linked library using DynamicLibrary.process(). check the example.dart file

**Comment by CaptainDario** [comment]
Is it only possible for android/ios, not desktop ?

**Comment by vm75** [comment]
Should work for any platform with statically linked ffi.

**Comment by vm75** [comment]
FYI @CaptainDario , I am not very happy with the project organization and plan to make some changes.
To start with, I plan to make pure wasm-ffi separate from the bridging utility and put the latter in a different project.
Hopefully, that will make it a bit cleaner and easier to use.

**Comment by vm75** [comment]
Some major changes in wasm_ffi v2.0.0. you will need universal_ffi for the other.
I have added some documentation. Hope it helps

**Comment by vm75** [comment]
sorry about the confusion. you may safely ignore native-ffi. it is just the new repository name which contains the other two.

- wasm_ffi : purely wasm support for web in the form of ffi
- universal_ffi: the combines dart:ffi & wasm_ffi to provide ffi for all platforms.

the idea is that if you use universal_ffi, you should get all platform support.

**Comment by vm75** [comment]
i have updated readme. hopefully it is less confusing. appreciate the feedback

**Comment by CaptainDario** [comment]
I am trying to use your new package but am encountering this

```dart
../lib/mecab_dart.dart:36:48: Error: The getter 'memory' isn't defined for the class 'DynamicLibrary'.
 - 'DynamicLibrary' is from 'dart:ffi'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'memory'.
    }, mecabDartFfi.mecabDartFfiHelper.library.memory);
                                               ^^^^^^
Target kernel_snapshot_program failed: Exception

Command PhaseScriptExecution failed with a nonzero exit code
** BUILD FAILED **
```
Any ideas?

**Comment by CaptainDario** [comment]
I am using universal_ffi, like this

```dart
mecabDartFfiHelper = (await FfiHelper.load("", options: {"is-statically-linked"}));

...

ffi.using((ffi.Arena arena) {
  mecabDartFfi.mecabPtr = mecabDartFfi.initMecabFfi(
    options.toNativeUtf8(), dictDir.toNativeUtf8());
}, mecabDartFfi.mecabDartFfiHelper.library.memory);
```

**Comment by vm75** [comment]
seems right. which platform?

**Comment by CaptainDario** [comment]
I am running on MacOS.

**Comment by vm75** [comment]
let me try it out. appreciate your patience.

**Comment by vm75** [comment]
could you share how you have aliased imports?

**Comment by vm75** [comment]
This works for me in my universal_ffi example:
`
  return using((Arena arena) {
    final cString = name.toNativeUtf8(allocator: arena).cast<Char>();
    final helloStr = bindings.hello(cString).cast<Utf8>().toDartString();
    final sizeOfInt = bindings.intSize();
    final sizeOfBool = bindings.boolSize();
    final sizeOfPointer = bindings.pointerSize();
    return Result(helloStr, sizeOfInt, sizeOfBool, sizeOfPointer);
  }, ffiHelper.library.memory);
`

**Comment by vm75** [comment]
@CaptainDario , I have deprecated the confusing use of 'memory' and have instead called it 'allocator'. memory will be there for some time.

I tried recreating your error by trying different import definition, but am not able to. not sure if your code is split across two separate files with different import definition.

I do realize that my sweeping changes can be very disruptive and will support where possible.

**Comment by CaptainDario** [comment]
Hey, thank you for all your help!
I think this package is truly great and many people will use it so I am happy to contribute even if I just test it.

It seems like there is something going on when using the `DynamicLibrary.process()` equivalent of this library.
If I manually cast the returned library to `universal_ffi.DynamicLibrary` it works as expected, but even the linter tells me this cast is unnecessary.

This works

<img width="893" alt="image" src="https://github.com/user-attachments/assets/81f4a326-98e5-4040-886f-432f87cd74fe" />

This does not

<img width="893" alt="image" src="https://github.com/user-attachments/assets/1719cee2-98a9-4713-996a-e7e4c1433ca1" />

**Comment by vm75** [comment]
If this is the only wasm being included, you can use standard 'using' without any trouble. I saw that you had used safeUsing in the branch. Does that also give trouble?

**Comment by CaptainDario** [comment]
How can I use safeUsing? It does not seem to be defined in ffi_utils

**Comment by CaptainDario** [comment]
@vm75 did you change something how libraries are loaded?

On web loading my library like

`final wrapper = (await FfiWrapper.load("assets/blobs/libmecab.js"));`

worked, but using the new `FfiHelper`-class it does not work anymore

` ffiHelper = (await FfiHelper.load("assets/blobs/libmecab.js"));`

**Comment by vm75** [comment]
it is in FfiHelper (formerly FfiWrapper).

**Comment by CaptainDario** [comment]
Yes, this works

```dart
    mecabDartFfi = MecabDartFfi();
    await mecabDartFfi.init();

    mecabDartFfi.mecabDartFfiHelper.safeUsing((ffi.Arena arena) {
      mecabDartFfi.mecabPtr = mecabDartFfi.initMecabFfi(
        options.toNativeUtf8(), dictDir.toNativeUtf8());
    }, (mecabDartFfi.mecabDartFfiHelper.library).allocator);
    
```

**Comment by CaptainDario** [comment]
The library that I am using uses fopen on the c-side, which worked previously on the web just fine when loading the files into the wasm filesystem. However, I cannot get it to work now.
The wasm library itself loads fine, but the files cannot be loaded, do you have any idea on this?

**Comment by vm75** [comment]
> Yes, this works
> 
> ```dart
>     mecabDartFfi = MecabDartFfi();
>     await mecabDartFfi.init();
> 
>     mecabDartFfi.mecabDartFfiHelper.safeUsing((ffi.Arena arena) {
>       mecabDartFfi.mecabPtr = mecabDartFfi.initMecabFfi(
>         options.toNativeUtf8(), dictDir.toNativeUtf8());
>     }, (mecabDartFfi.mecabDartFfiHelper.library).allocator);
>     
> ```

With safeUsing, you don't need to provide allocator.

**Comment by vm75** [comment]
> The library that I am using uses fopen on the c-side, which worked previously on the web just fine when loading the files into the wasm filesystem. However, I cannot get it to work now. The wasm library itself loads fine, but the files cannot be loaded, do you have any idea on this?

FS support on wasm is not very clear to me. There is some support in WASI, but I haven't tried it yet

**Comment by CaptainDario** [comment]
Well, clearing flutter and the browser cache solved this problem

**Comment by CaptainDario** [comment]
I guess this issue can now be closed, thank you for your help and also for this great package!
